//ALERT TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//AUTH TYPES
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
//PROFILE TYPES
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const RECORD_SESSION = 'RECORD_SESSION';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
//EXERCISE TYPES
export const EXERCISE_ERROR = 'EXERCISE_ERROR';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_MUSCLE = 'GET_MUSCLE';