//ALERT TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//AUTH TYPES
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
//PROFILE TYPES
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const RECORD_SESSION = 'RECORD_SESSION';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
//EXERCISE TYPES
export const EXERCISE_ERROR = 'EXERCISE_ERROR';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_MUSCLE = 'GET_MUSCLE';
//ROUTINE TYPES
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_ROUTINE = 'CREATE_ROUTINE';
export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const EDIT_ROUTINE = 'EDIT_ROUTINE';
export const EDIT_WORKOUT = 'EDIT_WORKOUT';
export const GET_ROUTINE = 'GET_ROUTINE';
export const GET_ROUTINES = 'GET_ROUTINES';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const ROUTINE_ERROR = 'ROUTINE_ERROR';
export const SAVE_ROUTINE = 'SAVE_ROUTINE';
export const UNSAVE_ROUTINE = 'UNSAVE_ROUTINE';
export const UPDATE_RECORD = 'UPDATE_RECORD';
//STORE TYPES
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL';
export const CREATE_METHOD = 'CREATE_METHOD';
export const DELETE_METHOD = 'DELETE_METHOD';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EMPTY_CART = 'EMPTY_CART';
export const GET_CART = 'GET_CART';
export const GET_METHODS = 'GET_METHODS';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PROCESS_PURCHASE = 'PURCHASE_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SET_LOADING = 'SET_LOADING';
export const STORE_ERROR = 'STORE_ERROR';
//POST TYPES
export const CREATE_POST = 'CREATE_POST';
export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const COMMENT_POST = 'COMMENT_POST';
export const UNCOMMENT_POST = 'UNCOMMENT_POST';
//ARTICLE TYPES
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const USERS_ARTICLES = 'USERS_ARTICLES';
export const SINGLE_ARTICLE = 'SINGLE_ARTICLE';
export const COMMUNITY_ARTICLE = 'COMMUNITY_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const FAVORITE_ARTICLE = 'FAVORITE_ARTICLE';
export const UNFAVORITE_ARTICLE = 'UNFAVORITE_ARTICLE';
export const COMMENT_ARTICLE = 'COMMENT_ARTICLE';
export const UNCOMMENT_ARTICLE = 'UNCOMMENT_ARTICLE';
//USER TYPES
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';