//ALERT TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//AUTH TYPES
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
//PROFILE TYPES
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const RECORD_SESSION = 'RECORD_SESSION';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
//EXERCISE TYPES
export const EXERCISE_ERROR = 'EXERCISE_ERROR';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_MUSCLE = 'GET_MUSCLE';
//ROUTINE TYPES
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_ROUTINE = 'CREATE_ROUTINE';
export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const EDIT_ROUTINE = 'EDIT_ROUTINE';
export const EDIT_WORKOUT = 'EDIT_WORKOUT';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const SAVE_ROUTINE = 'SAVE_ROUTINE';
export const UNSAVE_ROUTINE = 'UNSAVE_ROUTINE';
export const UPDATE_RECORD = 'UPDATE_RECORD';